import mongoose, { Schema, Types } from 'mongoose';

const FlightDetailsSchema = new Schema({
    userId: { type: Schema.Types.ObjectId, ref: "User" },
    ident: String,
    ident_icao: String,
    ident_iata: String,
    fa_flight_id: String,
    operator: String,
    operator_icao: String,
    operator_iata: String,
    flight_number: String,
    registration: String,
    atc_ident: String,
    inbound_fa_flight_id: String,
    codeshares: [String],
    codeshares_iata: [String],
    blocked: Boolean,
    diverted: Boolean,
    cancelled: Boolean,
    position_only: Boolean,
    origin: {
        code: String,
        code_icao: String,
        code_iata: String,
        code_lid: String,
        timezone: String,
        name: String,
        city: String,
        airport_info_url: String,
    },
    destination: {
        code: String,
        code_icao: String,
        code_iata: String,
        code_lid: String,
        timezone: String,
        name: String,
        city: String,
        airport_info_url: String,
    },
    departure_delay: Number,
    arrival_delay: Number,
    filed_ete: Number,
    foresight_predictions_available: Boolean,
    scheduled_out: String,
    estimated_out: String,
    actual_out: String,
    scheduled_off: String,
    estimated_off: String,
    actual_off: String,
    scheduled_on: String,
    estimated_on: String,
    actual_on: String,
    scheduled_in: String,
    estimated_in: String,
    actual_in: String,
    progress_percent: Number,
    status: String,
    aircraft_type: String,
    route_distance: Number,
    filed_airspeed: Number,
    filed_altitude: Number,
    route: String,
    baggage_claim: String,
    seats_cabin_business: Number,
    seats_cabin_coach: Number,
    seats_cabin_first: Number,
    gate_origin: String,
    gate_destination: String,
    terminal_origin: String,
    terminal_destination: String,
    flight: {
        date: Date,
        flight_id: String,
        aircraft_id: String,
        aircraft_type: String,
        from: String,
        to: String,
        out: [String],
        in: [String],
    },
    time: {
        total_time: Number,
        pic: String,
        sic: String,
        night: Number,
        xc: String,
        actual_inst: String,
    },
    duty: {
        on_duty: [String],
        off_duty: [String]
    },
    crew: {
        pic_p1_crew: String,
        sic_p2_crew: String,
    },
    landings: {
        day_t_o: String,
        day_ldg: String,
        night_t_o: String,
        night_ldg: String,
    },
    operations: [{
        apr: String,
        count: Number,
        rwy: String,
        icao: String,
    }],
    passengers: [String],
    notes: String
});


const FlightDetailsModel = mongoose.model('FlightDetails', FlightDetailsSchema);

export default FlightDetailsModel;
